config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'namespaces#index'
  resources :namespaces
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/namespace.rb
class Namespace < ApplicationRecord
  validates :name, :assyst_svd, :owner_email, :technical_owner_email,
            :support_document, :support_document_uri, presence: true
  validates :arb, numericality: { greater_than_or_equal_to: 0 }
  validates :image_file_name, format: {
    with: /\w+\.(jpg|png)\z/i,
    message: "must be a JPG or PNG image"
  }

  VENDORS = %w(none bob larry)
  # validates :vendor_supported, inclusion: { in: VENDORS }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/namespaces_controller.rb
class NamespacesController < ApplicationController
  def index
    @namespaces = Namespace.all
  end

  def show
    @namespace = Namespace.find(params[:id])
  end

  def new
    @namespace = Namespace.new
  end

  def edit
    @namespace = Namespace.find(params[:id])
  end

  def update
    @namespace = Namespace.find(params[:id])
    if @namespace.update(namespace_params)
      redirect_to @namespace, notice: 'Namespace successfully updated!'
    else
      render :edit
    end
  end

  def create
    @namespace = Namespace.new(namespace_params)
    if @namespace.save
      redirect_to @namespace, notice: 'Namespace successfully created!'
    else
      render :new
    end
  end

  def destroy
    @namespace = Namespace.find(params[:id])
    @namespace.destroy

    redirect_to @namespace, alert: 'Namespace successfully deleted!'
  end

  private

  def namespace_params
    params.require(:namespace)
          .permit(:name, :arb, :dept_name, :assyst_svd, :vendor_supported,
                  :owner_email, :technical_owner_email, :support_document,
                  :support_document_uri, :image_file_name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/namespaces_helper.rb
module NamespacesHelper
end

app/views/layouts/_flash.html.erb
<% if flash[:notice] %>
  <div class="flash notice">
    <%= flash[:notice] %>
  </div>
<% end %>

<% if flash[:alert] %>
  <div class="flash alert">
    <%= flash[:alert] %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <p>
    Copyright &copy; 2020-<%= Time.now.year %>
    <%= link_to 'toller inc','https://toller.io' %>
  </p>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav>
    <%= link_to image_tag('logo'), root_path %>
    <ul>
      <li>
        <%= link_to "All Namespaces", namespaces_path %>
      </li>
    </ul>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Toller</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>

    <div class="content">
      <%= render "layouts/flash" %>
      
      <%= yield %>
    </div>

    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/namespaces/_form.html.erb
<%= form_with(model: namespace, local: true) do |f| %>

  <%= render "shared/errors", object: namespace %>
  
  <%= f.label :name %>
  <%= f.text_field :name, autofocus: true %>

  <%= f.label :arb %>
  <%= f.number_field :arb %>  

  <%= f.label :dept_name %>
  <%= f.text_field :dept_name %>  

  <%= f.label :assyst_svd %>
  <%= f.text_field :assyst_svd %>

  <%= f.label :vendor_supported %>
  <%= f.select :vendor_supported, Namespace::VENDORS %> 

  <%= f.label :owner_email %>
  <%= f.text_field :owner_email %> 

  <%= f.label :technical_owner_email %>
  <%= f.text_field :technical_owner_email %> 

  <%= f.label :support_document %>
  <%= f.text_field :support_document %> 

  <%= f.label :support_document_uri %>
  <%= f.text_field :support_document_uri %> 

  <%= f.label :image_file_name %>
  <%= f.text_field :image_file_name %> 

  <%= f.submit %>
<% end %>

app/views/namespaces/edit.html.erb
<h1>
  Editing <%= @namespace.name %>
</h1>

<%= render "form", namespace: @namespace %>

app/views/namespaces/index.html.erb
<% @namespaces.each do |namespace| %>
  <section class="namespace">
    <div class="image">
       <%= image_tag namespace.image_file_name %>
    </div>
    <div class="summary">
      <h2>
        <%= link_to namespace.name, namespace %>
      </h2>
      <h3>
        <%= namespace.arb %>
      </h3>
    </div>
  </section>
<% end %>

<section class="admin">
  <%= link_to "Add new namespace", new_namespace_path, class: "button" %>
</section>

app/views/namespaces/new.html.erb
<h1>Create a New Namespace</h1>

<%= render "form", namespace: @namespace %>

app/views/namespaces/show.html.erb
<section class="namespace-details">
  <div class="image">
    <%= image_tag @namespace.image_file_name %>
  </div>
  <div class="details">
    <h1>
      <%= @namespace.name %>
    </h1>
  </div>
</section>

<section class="admin">
  <%= link_to "Edit", edit_namespace_path(@namespace), class: "button" %>
  <%= link_to "Delete", @namespace, class: "button", method: :delete,
                  data: { confirm: "Really?!" } %>
</section>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <section class="errors">
    <h2>
      Oops! Your form could not be saved.
    </h2>
    <h3>
      Please correct the following
      <%= pluralize(object.errors.size, "error") %>:
    </h3>
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </section>
<% end %>